name: PR Presubmit
on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration
  pull_request:
    types: [opened, synchronize]

jobs:
  prepare_commit_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Prepare Commit Data
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
        run: |
          echo "PR: ${{ github.event.pull_request.number }}"
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          echo "HEAD REF: ${{ github.event.pull_request.head.ref }}"
          echo "HEAD SHA: $HEAD_SHA"
          echo "BASE REF: ${{ github.event.pull_request.base.ref }}"
          echo "BASE SHA: $BASE_SHA"
          git rev-parse HEAD
          git log -5
          git diff $HEAD_SHA..$BASE_SHA

      - name: Push Commit Data
        # https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow
        uses: actions/upload-artifact@v2
        with:
          name: echo_commit_data
          path: echo_commit_data.sh
