name: Publishing Release
on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build_and_test_cpu:
    name: Build and Test (macOS only)
    strategy:
      matrix:
        include:
          - os: macos-latest
            python: 3.6
            with_cc: OFF
          - os: macos-latest
            python: 3.7
            with_cc: OFF
          - os: macos-latest
            python: 3.8
            with_cc: OFF
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download Pre-Built LLVM 10.0.0
        run: |
          python misc/ci_download.py
          mkdir taichi-llvm
          cd taichi-llvm
          unzip ../taichi-llvm.zip
        env:
          CI_PLATFORM: ${{ matrix.os }}

      - name: Build
        run: |
          export TAICHI_REPO_DIR=`pwd`
          export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
          export CXX=clang++
          python misc/ci_setup.py ci

      - name: Build Python Wheel
        run: |
          export TAICHI_REPO_DIR=`pwd`
          export PATH=$TAICHI_REPO_DIR/bin:$PATH
          export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
          export PYTHONPATH=$TAICHI_REPO_DIR/python
          cd python
          python build.py build

      - name: Archive Wheel Artifacts
        uses: actions/upload-artifact@v2
        with:
          # While ${{ github.ref }} does provide the release tag, it is of
          # format `refs/tags/<tag_name>`, which isn't a valid file path.
          name: taichi-py${{ matrix.python }}-${{ matrix.os }}.whl
          path: python/dist/*.whl

      # TODO(#1580): Upload to PyPI. Need to set up PYPI_PWD in the secrets first.
      - name: Fake PyPI Upload
        env:
          PYPI_PWD: "fakefakefake"
        run: |
          export TAICHI_REPO_DIR=`pwd`
          export PATH=$TAICHI_REPO_DIR/bin:$PATH
          export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
          export PYTHONPATH=$TAICHI_REPO_DIR/python
          cd python
          python build.py try_upload --skip_build
